# Generated by Django 4.0 on 2021-12-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='advantages',
        ),
    ]
