# Generated by Django 4.0 on 2021-12-27 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_tag_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.job')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.tag')),
            ],
        ),
    ]
